import { useState, useEffect, useRef } from 'react';
import { NavLink, Routes, Route, useNavigate, useLocation, Link } from 'react-router-dom';
import { Plus, House, Tv, Drama, Zap, Folder, ChevronRight, HelpCircle, FileText, Trophy, MessagesSquare, Monitor, Bell, Crown, Coins, Menu, X, ArrowRight, ChevronsUp, LogOut, Settings, CalendarCheck, Wallet, Settings2 } from 'lucide-react';
import { StudioProvider, useStudio } from './studio';
import { Composer, IconButton, Tabs, type ComposerValue } from './components';
import { industries, shortcuts } from './catalog';
import { ProjectsPage, AssetsPage, SkillsPage, TVPage, AgentConfigPage } from './pages';
import { Overlays } from './overlays';
import Editor from './editor';
import Stage from './stage';
import { post } from './api';

function Shell(){
 const{data,loading,error,refresh,open,createProject,notify}=useStudio();const location=useLocation();const navigate=useNavigate();const[promo,setPromo]=useState(()=>localStorage.getItem('promo-hidden')!=='1');const[mobile,setMobile]=useState(false);const[account,setAccount]=useState(false);const[industry,setIndustry]=useState('个人/自媒体');const[session,setSession]=useState(()=>localStorage.getItem('local-session')!=='off');const accountRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{setMobile(false);setAccount(false);document.title=location.pathname.startsWith('/space')?'创作画布 · OiiOii 本地工作室':'OiiOii · 本地创作工作室';},[location.pathname]);
 useEffect(()=>{if(!account)return;const hide=(e:MouseEvent)=>{if(!accountRef.current?.contains(e.target as Node))setAccount(false);};document.addEventListener('mousedown',hide);return()=>document.removeEventListener('mousedown',hide);},[account]);
 const editor=location.pathname.startsWith('/space/');const stage=location.pathname==='/stage';const home=['/','/zh','/zh/'].includes(location.pathname);
 const hidePromo=()=>{setPromo(false);localStorage.setItem('promo-hidden','1');};
 const logIn=()=>open('login',{done:()=>{setSession(true);localStorage.setItem('local-session','on');}});
 if(loading)return <div className="boot-screen"><b>OiiOii</b><span className="loader"/></div>;
 if(error)return <div className="boot-screen"><h2>工作室暂时无法连接</h2><p>{error}</p><button className="button primary" onClick={()=>void refresh()}>重新连接</button></div>;
 return <div className={`app ${promo&&!editor&&!stage?'has-promo':''} ${editor?'editor-app':''}`}>
 {!editor&&!stage&&<>{promo&&<div className="promo"><span className="promo-dot"/><span>双节超值特惠，年付会员享3倍盒饭赠送，Seedance 2.5 720P 低至0.32元/秒</span><button onClick={()=>open('pricing')}>立即抢购</button><IconButton label="关闭活动横幅" onClick={hidePromo}><X size={16}/></IconButton></div>}
 <aside className={`sidebar ${mobile?'open':''}`}><Link to="/" className="brand" aria-label="回到首页">OiiOii</Link><nav><button className="nav-link" onClick={()=>session?open('new-project'):logIn()}><Plus size={17}/><span>新建项目</span></button><NavLink to="/" end className="nav-link"><House size={17}/><span>Oii 工作室</span></NavLink><NavLink to="/oii-tv" className="nav-link"><Tv size={17}/><span>Oii TV</span></NavLink><NavLink to="/asset" className="nav-link"><Drama size={17}/><span>资产</span></NavLink><NavLink to="/skill" className="nav-link"><Zap size={18}/><span>技能</span></NavLink><NavLink to="/agent-config" className="nav-link"><Settings2 size={17}/><span>Agent 配置</span></NavLink><div className="nav-separator"/><NavLink to="/project" className="nav-link"><Folder size={16}/><span>我的项目</span><ChevronRight size={15}/></NavLink><div className="recent-projects">{data.projects.filter(p=>!p.trashed).slice(0,5).map(p=><Link key={p.id} to={`/space/${p.id}`}><span className="project-mini">{p.cover?<img src={p.cover} alt=""/>:<Folder size={14}/>}</span><span>{p.name}</span></Link>)}</div></nav><div className="sidebar-bottom"><button className="desktop-promo" onClick={()=>open('desktop')}><Monitor size={16}/>下载桌面端</button><div className="sidebar-tools"><IconButton label="帮助" onClick={()=>open('help')}><HelpCircle size={15}/></IconButton><IconButton label="创作许可协议" onClick={()=>open('license')}><FileText size={15}/></IconButton><IconButton label="活动" onClick={()=>open('activity')}><Trophy size={15}/></IconButton><IconButton label="联系我们" onClick={()=>open('contact')}><MessagesSquare size={15}/></IconButton></div></div></aside>
 {mobile&&<button className="sidebar-scrim" aria-label="关闭导航" onClick={()=>setMobile(false)}/>}
 <header className="topbar"><IconButton label="打开导航" className="mobile-menu" onClick={()=>setMobile(!mobile)}><Menu size={21}/></IconButton>{home&&<Tabs values={industries} value={industry} onChange={setIndustry} pills/>}<div className="topbar-right"><button className="announcement" onClick={()=>navigate('/stage')}><img src="/assets/stage.webp" alt=""/><span>AI 3D 预演功能上线</span></button><div className="notification-anchor"><IconButton label="消息" onClick={()=>open('notifications')}><Bell size={18}/></IconButton>{data.notifications.some(n=>!n.read)&&<span className="badge-counter">{data.notifications.filter(n=>!n.read).length}</span>}</div><button className="membership" onClick={()=>open('pricing')}><Crown size={17}/><span>会员订阅</span><small>最低18折</small></button>{session?<div className="account-anchor" ref={accountRef}><button className="account-button" onClick={()=>setAccount(!account)} aria-label="账户菜单" aria-expanded={account}><Coins size={15}/><span>{data.profile.credits}</span><b>LOCAL</b><img src={data.profile.avatar} alt="用户头像"/></button>{account&&<div className="account-menu"><div className="account-identity"><img src={data.profile.avatar} alt=""/><div><strong>{data.profile.name}</strong><small>本地账户</small></div></div><button onClick={async()=>{try{await post('/checkin',{});await refresh();notify('今日签到已记录，本地测试积分 +10');}catch(e){notify((e as Error).message,true);}}}><CalendarCheck size={17}/>每日签到</button><button onClick={()=>{open('balance');setAccount(false);}}><Wallet size={17}/>余额</button><button onClick={()=>{open('settings');setAccount(false);}}><Settings size={17}/>设置</button><button onClick={()=>{setSession(false);localStorage.setItem('local-session','off');setAccount(false);notify('已退出本地会话');}}><LogOut size={17}/>退出登录</button></div>}</div>:<button className="button primary" onClick={logIn}>免费注册 / 登录</button>}</div></header></>}
 <main className={editor||stage?'fullscreen-content':'main-content'}><Routes><Route path="/" element={<Home industry={industry} session={session} login={logIn}/>}/><Route path="/zh/" element={<Home industry={industry} session={session} login={logIn}/>}/><Route path="/project" element={<ProjectsPage/>}/><Route path="/asset" element={<AssetsPage/>}/><Route path="/skill" element={<SkillsPage/>}/><Route path="/agent-config" element={<AgentConfigPage/>}/><Route path="/oii-tv" element={<TVPage/>}/><Route path="/space/:id" element={<Editor/>}/><Route path="/stage" element={<Stage/>}/><Route path="*" element={<div className="not-found"><h1>页面不存在</h1><button className="button" onClick={()=>navigate('/')}>返回工作室</button></div>}/></Routes></main><Overlays/>
 </div>;
}
function Home({industry,session,login}:{industry:string;session:boolean;login:()=>void}){
 const{data,createProject,open}=useStudio();const navigate=useNavigate();const[prompt,setPrompt]=useState('');const[skill,setSkill]=useState('');
 const submit=async(v:ComposerValue)=>{if(!session){login();return;}const p=await createProject(v.prompt.slice(0,24),v.skill||industry,v.prompt);if(p)sessionStorage.setItem(`draft-${p.id}`,JSON.stringify(v));};
 const select=(label:string,value:string)=>{if(label==='自由画布'){void createProject();return;}if(label==='AI 3D 预演台'){navigate('/stage');return;}setSkill(value);};
 return <><section className="home-stage" onDoubleClick={e=>{if(e.target===e.currentTarget)void createProject();}}><div className="home-creation"><div className="home-title"><img src="/assets/writer.png" alt=""/><h1>OiiOii {industry} Agent</h1></div><p className="canvas-hint"><span>⌁ 双击左键</span>，进入自由画布</p><Composer onSubmit={submit} initialPrompt={prompt} initialSkill={skill}/><div className="shortcuts">{shortcuts.map(([label,value,img])=><button key={label} className={`shortcut shortcut-${img}`} onClick={()=>select(label,value)}><img src={`/assets/${img}.webp`} alt=""/><span>{label}</span></button>)}<IconButton label="查看全部技能" className="all-skills" onClick={()=>navigate('/skill')}><ArrowRight size={18}/></IconButton></div></div></section><section className="home-showcase"><div className="section-title"><h2>{industry==='个人/自媒体'?'社媒爆款':`${industry}精选`}</h2><Link to="/oii-tv">上划查看更多<ChevronsUp size={14}/></Link></div><div className="work-grid">{data.works.slice(0,8).map(w=><button className="work-card" key={w.id} onClick={()=>open('work',w)}><img src={w.image} alt={w.title}/><span>{w.title}</span></button>)}</div><div className="quick-prompts"><h2>开始新的创作</h2>{['一个关于夏天与重逢的治愈故事','为我的品牌制作 15 秒产品短片','设计一位东方奇幻故事的主角'].map(p=><button key={p} onClick={()=>{setPrompt(p);window.scrollTo({top:0,behavior:'smooth'});}}>{p}<ArrowRight size={16}/></button>)}</div></section><footer className="site-footer"><span className="brand">OiiOii</span><span>本地创作工作室 · 独立复刻项目</span><button onClick={()=>open('help')}>帮助</button><button onClick={()=>open('settings')}>服务设置</button></footer></>;
}
export default function App(){return <StudioProvider><Shell/></StudioProvider>;}
