import { useEffect, useRef, useState, type ReactNode, type ButtonHTMLAttributes } from 'react';
import { ArrowUp, Plus, Zap, Box, Shapes, Drama, Lightbulb, ChevronDown, X, Search, Image, Film, Music, Check, Upload, LoaderCircle } from 'lucide-react';
import { useStudio } from './studio';
import { modelGroups } from './catalog';
import type { Asset, AgentKind } from './types';
export function IconButton({label,children,className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{label:string}){return <button type="button" className={`icon-button ${className}`} title={label} aria-label={label} {...props}>{children}</button>;}
export function SearchBox({value,onChange,placeholder='搜索'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="search-box"><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} aria-label={placeholder}/><Search size={17}/></label>;}
export function Tabs({values,value,onChange,pills=false}:{values:string[];value:string;onChange:(v:string)=>void;pills?:boolean}){return <div className={pills?'tabs pills':'tabs'} role="tablist">{values.map(v=><button type="button" role="tab" aria-selected={value===v} key={v} className={value===v?'active':''} onClick={()=>onChange(v)}>{v}</button>)}</div>;}
export function Empty({title,children,icon=<Box size={32}/>}:{title:string;children?:ReactNode;icon?:ReactNode}){return <div className="empty-state">{icon}<h3>{title}</h3>{children}</div>;}
export function Modal({title,children,onClose,wide=false,className=''}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean;className?:string}){
 const ref=useRef<HTMLDivElement>(null);
 const closeRef=useRef(onClose);closeRef.current=onClose;
 useEffect(()=>{const prior=document.activeElement as HTMLElement;const old=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){closeRef.current();return;}if(e.key==='Tab'){const els=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,textarea,select,[tabindex="0"]')||[]).filter(el=>el.offsetParent!==null);const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);prior?.focus();};},[]);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title} className={`modal ${wide?'wide':''} ${className}`}><header className="modal-header"><h2>{title}</h2><IconButton label="关闭" onClick={onClose}><X size={19}/></IconButton></header>{children}</div></div>;
}
export type ComposerValue={prompt:string;model:string;kind:string;style:string;skill:string;assets:Asset[];ratio:string;resolution:string;duration:number};
export function Composer({compact=false,onSubmit,initialPrompt='',initialSkill='',busy=false}:{compact?:boolean;onSubmit:(v:ComposerValue)=>void;initialPrompt?:string;initialSkill?:string;busy?:boolean}){
 const {data,open,upload,notify}=useStudio();const[prompt,setPrompt]=useState(initialPrompt);const[model,setModel]=useState('Agent');const[kind,setKind]=useState('Agent');const[style,setStyle]=useState('');const[skill,setSkill]=useState(initialSkill);const[assets,setAssets]=useState<Asset[]>([]);const[menu,setMenu]=useState('');const[group,setGroup]=useState('图片');const[ratio,setRatio]=useState('16:9');const[resolution,setResolution]=useState('720p');const[duration,setDuration]=useState(5);const[uploading,setUploading]=useState(false);const fileRef=useRef<HTMLInputElement>(null);const area=useRef<HTMLTextAreaElement>(null);const wrap=useRef<HTMLDivElement>(null);
 const configuredGroups=(()=>{const map:Record<string,{name:string;description:string;badge?:string}[]>={图片:[],视频:[],音频:[]};const labels:Record<string,AgentKind>={图片:'图文',视频:'视频',音频:'音频'};for(const source of data.agentSources){const label=Object.entries(labels).find(([,value])=>value===source.kind)?.[0];if(source.enabled&&label)map[label].push(...source.models);}return Object.fromEntries(Object.entries(map).map(([key,items])=>[key,items.length?items:modelGroups[key]]));})();
 useEffect(()=>{setPrompt(initialPrompt);},[initialPrompt]);useEffect(()=>{setSkill(initialSkill);},[initialSkill]);
 useEffect(()=>{if(!menu)return;const close=(e:MouseEvent)=>{if(!wrap.current?.contains(e.target as Node))setMenu('');};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close);},[menu]);
 const addFiles=async(files:File[])=>{setUploading(true);try{const added=await upload(files);setAssets(a=>[...a,...added].slice(0,10));}finally{setUploading(false);}};
 const submit=()=>{if(!prompt.trim()||busy||uploading)return;onSubmit({prompt:prompt.trim(),model,kind,style,skill,assets,ratio,resolution,duration});setPrompt('');setAssets([]);};
 return <div className={`composer ${compact?'compact':''}`} ref={wrap} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void addFiles(Array.from(e.dataTransfer.files));}}>
  <input type="file" ref={fileRef} hidden multiple accept="image/*,video/*,audio/*" onChange={e=>{void addFiles(Array.from(e.target.files||[]));e.target.value='';}}/>
  {!compact&&<button className="upload-square" aria-label="上传图片" title="上传图片、视频或音频" onClick={()=>fileRef.current?.click()}>{uploading?<LoaderCircle className="spin" size={19}/>:<Plus size={23}/>}</button>}
  {(assets.length>0||style||skill)&&<div className="composer-tags">{assets.map(a=><span className="reference-chip" key={a.id}>{a.mime.startsWith('image/')&&<img src={a.url} alt=""/>}{a.name}<button aria-label={`移除 ${a.name}`} onClick={()=>setAssets(v=>v.filter(x=>x.id!==a.id))}><X size={12}/></button></span>)}{style&&<span className="reference-chip"><Shapes size={13}/>{style}<button aria-label="移除风格" onClick={()=>setStyle('')}><X size={12}/></button></span>}{skill&&<span className="reference-chip"><Zap size={13}/>{skill}<button aria-label="移除技能" onClick={()=>setSkill('')}><X size={12}/></button></span>}</div>}
  <textarea ref={area} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={compact?'描述你的创作需求':'描述你的创作需求，也可以试试使用 Skill 技能、模板'} aria-label="创作需求" onPaste={e=>{const files=Array.from(e.clipboardData.files);if(files.length){e.preventDefault();void addFiles(files);}}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit();}}}/>
  {kind!=='Agent'&&<div className="generation-options"><select aria-label="画面比例" value={ratio} onChange={e=>setRatio(e.target.value)}>{['16:9','9:16','1:1','4:3','3:4'].map(v=><option key={v}>{v}</option>)}</select><select aria-label="清晰度" value={resolution} onChange={e=>setResolution(e.target.value)}>{(kind==='图片'?['1K','2K','4K']:['480p','720p','1080p']).map(v=><option key={v}>{v}</option>)}</select>{kind==='视频'&&<select aria-label="视频时长" value={duration} onChange={e=>setDuration(Number(e.target.value))}>{[5,10,15,30].map(v=><option value={v} key={v}>{v} 秒</option>)}</select>}</div>}
  <div className="composer-toolbar">{compact&&<IconButton label="上传素材" onClick={()=>fileRef.current?.click()}><Plus size={19}/></IconButton>}
    <button className="tool-button" onClick={()=>open('skill-picker',{select:(s:string)=>setSkill(s)})}><Zap size={18}/><span>技能</span><ChevronDown size={12}/></button>
    <div className="model-anchor"><button className={`tool-button ${menu?'selected':''}`} aria-expanded={!!menu} onClick={()=>setMenu(menu?'':'model')}><Box size={18}/><span>{model}</span><ChevronDown size={12}/></button>
    {menu==='model'&&<div className="model-menu"><div className="model-menu-title"><span>模型</span><button onClick={()=>{setModel('Agent');setKind('Agent');setMenu('');}}><Box size={16}/>Agent {kind==='Agent'&&<Check size={15}/>}</button></div><Tabs values={Object.keys(configuredGroups)} value={group} onChange={setGroup}/><div className="model-list">{(configuredGroups[group]||[]).map(m=><button key={m.name} onClick={()=>{setModel(m.name);setKind(group==='图片'?'图片':group);setResolution(group==='图片'?'2K':'720p');setMenu('');}}><span className="model-icon">{group==='图片'?<Image size={20}/>:group==='视频'?<Film size={20}/>:<Music size={20}/>}</span><span><strong>{m.name} {m.badge&&<em>{m.badge}</em>}</strong><small>{m.description}</small></span>{model===m.name&&<Check size={16}/>}</button>)}</div></div>}
    </div>
    <button className="tool-button" onClick={()=>open('styles',{select:(s:string)=>setStyle(s)})}><Shapes size={17}/><span>风格</span></button>
    <button className="tool-button" onClick={()=>open('asset-picker',{select:(a:Asset)=>{setAssets(v=>[...v,a]);notify(`已引用 ${a.name}`);}})}><Drama size={17}/><span>资产</span></button>
    <button className="tool-button template-button" onClick={()=>open('templates',{select:(s:string)=>{setPrompt(p=>p?`${p}\n${s}`:s);area.current?.focus();}})}><Lightbulb size={17}/><span>模板</span><i/></button>
    <button className="send-button" title="发送" aria-label="发送" disabled={!prompt.trim()||busy||uploading} onClick={submit}>{busy?<LoaderCircle size={17} className="spin"/>:<ArrowUp size={17}/>}<span>{busy?'生成中':'发送'}</span></button>
  </div>
 </div>;
}
export function FileDrop({onFiles,accept='image/*,video/*,audio/*',multiple=true}:{onFiles:(f:File[])=>void;accept?:string;multiple?:boolean}){const r=useRef<HTMLInputElement>(null);return <div className="file-drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();onFiles(Array.from(e.dataTransfer.files));}}><Upload size={27}/><button className="button" onClick={()=>r.current?.click()}>选择文件</button><p>图片、视频或音频 · 单个文件不超过 50 MB</p><input hidden ref={r} type="file" accept={accept} multiple={multiple} onChange={e=>onFiles(Array.from(e.target.files||[]))}/></div>;}
