import { useState, useEffect, useRef, useCallback, useMemo, createContext, useContext } from 'react';
import { useParams, Link, useNavigate } from 'react-router-dom';
import type { Editor as TldrawEditor } from 'tldraw';
import { TldrawCanvas, canvasFit, type DisplayNode } from './tldraw-canvas';
type Node<T> = {id:string;type:string;position:{x:number;y:number};data:T;selected?:boolean};
type Edge = CanvasEdge;
import { Plus, ArrowLeft, ChevronDown, MoreHorizontal, Share2, Upload, Download, Save, Undo2, Redo2, Type, Image, Film, MousePointer2, Hand, Map, Check, X, Trash2, Copy, Maximize2, PanelLeftClose, PanelLeftOpen, ListTodo, AlertCircle, LoaderCircle, Clapperboard, Pencil, Play, Link2, Folder, Grid2X2, Settings, Sparkles, FileText, Send, Music, MessagesSquare } from 'lucide-react';
import { useStudio } from './studio';
import { api, post, patch, downloadJson } from './api';
import { modelGroups } from './catalog';
import { Composer, IconButton, Modal, Empty, type ComposerValue } from './components';
import type { Project, CanvasNode, CanvasEdge, Message, Asset, Job, WorkflowNodeAction, WorkflowResult } from './types';
import { ProductionConversation, ProductionInspector, ProductionNode, ProductionProvider, productionNodes, useProduction } from './production';
import type { ProductionNodeData } from './production';
import Timeline from './timeline';
import { CharacterPopover, ImageLightbox } from './character-popover';

const NodeContext=createContext<{edit:(id:string)=>void;remove:(id:string)=>void;duplicate:(id:string)=>void;connect:(id:string)=>void}>({edit:()=>{},remove:()=>{},duplicate:()=>{},connect:()=>{}});
function StudioNode({id,data,selected}:{id:string;data:CanvasNode['data'];selected?:boolean}){const ctx=useContext(NodeContext);const mediaFrame=['图片','视频','音频'].includes(data.kind);return <div className={`studio-node ${mediaFrame?'media-frame':''} ${selected?'selected':''}`}><header><span className={`node-kind kind-${data.kind}`}>{data.kind}</span><strong>{data.title}</strong><button className="nodrag" title="编辑节点" aria-label={`编辑 ${data.title}`} onClick={()=>ctx.edit(id)}><Pencil size={14}/></button></header>{data.url?<div className="node-media">{data.mime?.startsWith('video/')?<video src={data.url} controls className="nodrag"/>:data.mime?.startsWith('audio/')?<audio src={data.url} controls className="nodrag"/>:<img src={data.url} alt={data.title}/>}</div>:mediaFrame?<div className="node-empty">{data.kind==='图片'?<Image size={38}/>:data.kind==='视频'?<Film size={38}/>:<Music size={38}/>}<span>选择素材或填写提示词后生成</span></div>:null}<div className="node-body"><p>{data.text||'添加内容'}</p></div><footer><span>{data.duration?`${data.duration}s`:data.kind}</span><button className="nodrag" aria-label={`连接 ${data.title}`} title="连接到另一个节点" onClick={()=>ctx.connect(id)}><Link2 size={13}/></button><button className="nodrag" aria-label={`复制 ${data.title}`} title="复制节点" onClick={()=>ctx.duplicate(id)}><Copy size={13}/></button><button className="nodrag" aria-label={`删除 ${data.title}`} title="删除节点" onClick={()=>ctx.remove(id)}><Trash2 size={13}/></button></footer></div>;}
export default function Editor(){const{id}=useParams();const[project,setProject]=useState<Project|null>(null);const[error,setError]=useState('');useEffect(()=>{let active=true;setProject(null);api<Project>(`/projects/${id}`).then(p=>{if(active)setProject(p);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[id]);if(error)return <div className="boot-screen"><p>{error}</p><Link className="button" to="/project">返回项目</Link></div>;if(!project)return <div className="boot-screen"><LoaderCircle className="spin"/></div>;return <ProjectEditor key={project.id} initial={project}/>;}
function ProjectEditor({initial}:{initial:Project}){
 const{data,open,notify,refresh}=useStudio();const navigate=useNavigate();const[category,setCategory]=useState(initial.category);const[productionLayout,setProductionLayout]=useState<Record<string,{x:number;y:number}>>(()=>{try{return JSON.parse(localStorage.getItem(`production-layout-v2-${initial.id}`)||'{}');}catch{return {};}});const productionMode=category!=='自由画布';const production=useProduction(initial.id,productionMode);const[nodes,setNodes]=useState<Node<CanvasNode['data']>[]>(initial.nodes as Node<CanvasNode['data']>[]);const[edges,setEdges]=useState<Edge[]>(initial.edges);const[messages,setMessages]=useState<Message[]>(initial.messages);const[clips,setClips]=useState(initial.clips);const[script,setScript]=useState(initial.script);const[name,setName]=useState(initial.name);const[chat,setChat]=useState(true);const[historyOpen,setHistoryOpen]=useState(false);const[minimap,setMinimap]=useState(false);const[pan,setPan]=useState(false);const[inspector,setInspector]=useState('');const[productionDetail,setProductionDetail]=useState('');const[characterSelection,setCharacterSelection]=useState<{id:string;slot:string}|null>(null);const[mediaPreview,setMediaPreview]=useState<{url:string;kind:string}|null>(null);const[showAdd,setShowAdd]=useState(false);const[menuPosition,setMenuPosition]=useState<{x:number;y:number}|null>(null);const[showTasks,setShowTasks]=useState(false);const[showTimeline,setShowTimeline]=useState(false);const[showScript,setShowScript]=useState(false);const[saveState,setSaveState]=useState('已保存');const[jobs,setJobs]=useState<Job[]>(data.jobs.filter(j=>j.projectId===initial.id));const[pendingJobs,setPendingJobs]=useState(0);const[history,setHistory]=useState<{nodes:Node<CanvasNode['data']>[];edges:Edge[];layout:Record<string,{x:number;y:number}>}[]>([]);const[future,setFuture]=useState<typeof history>([]);const tldrawEditor=useRef<TldrawEditor|null>(null);const canvasNodesRef=useRef<DisplayNode[]>([]);const rf={screenToFlowPosition:(point:{x:number;y:number})=>tldrawEditor.current?.screenToPage(point)||point,fitView:({nodes:target,padding}:{nodes?:DisplayNode[];padding?:number;duration?:number})=>canvasFit(tldrawEditor.current,target||canvasNodesRef.current,padding)};const uploadRef=useRef<HTMLInputElement>(null);const chatEnd=useRef<HTMLDivElement>(null);const chatMessagesRef=useRef<HTMLDivElement>(null);const draft=useRef<ComposerValue|undefined>(undefined);const latest=useRef<any>(null);const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);const queue=useRef(Promise.resolve());const revision=useRef(0);const[seedPrompt,setSeedPrompt]=useState('');const[sourceNodeId,setSourceNodeId]=useState('');const[connectingFrom,setConnectingFrom]=useState('');const projectRef=useRef(initial);const nodesRef=useRef(nodes);const edgesRef=useRef(edges);const messagesRef=useRef(messages);const scriptRef=useRef(script);
 useEffect(()=>{localStorage.setItem(`production-layout-v2-${initial.id}`,JSON.stringify(productionLayout));},[initial.id,productionLayout]);
 const[productionCardColors,setProductionCardColors]=useState<Record<string,string>>(()=>{try{return JSON.parse(localStorage.getItem(`production-card-colors-v1-${initial.id}`)||'{}');}catch{return {};}});
 useEffect(()=>{localStorage.setItem(`production-card-colors-v1-${initial.id}`,JSON.stringify(productionCardColors));},[initial.id,productionCardColors]);
 nodesRef.current=nodes;edgesRef.current=edges;messagesRef.current=messages;scriptRef.current=script;
 const busy=pendingJobs>0;
 const projectNodes=nodes.filter(n=>n.type!=='production');const projectNodeIds=new Set(projectNodes.map(n=>n.id));const payload={name,category,nodes:projectNodes.map(n=>({id:n.id,type:'studio',position:n.position,data:n.data})),edges:edges.filter(e=>projectNodeIds.has(e.source)&&projectNodeIds.has(e.target)).map(e=>({id:e.id,source:e.source,target:e.target})),messages,clips,script,cover:projectNodes.find(n=>n.data.url&&n.data.mime?.startsWith('image/'))?.data.url||''};
 latest.current=payload;
 const save=useCallback(async()=>{clearTimeout(timer.current);const value=structuredClone(latest.current);const r=++revision.current;setSaveState('保存中');const task=queue.current.catch(()=>{}).then(async()=>{try{const p=await patch<Project>(`/projects/${initial.id}`,value);projectRef.current=p;if(r===revision.current)setSaveState('已保存');}catch(e){setSaveState('保存失败');notify((e as Error).message,true);throw e;}});queue.current=task;await task;},[initial.id,notify]);
 useEffect(()=>{setSaveState('未保存');clearTimeout(timer.current);timer.current=setTimeout(()=>{void save().catch(()=>{});},650);return()=>clearTimeout(timer.current);},[name,category,nodes,edges,messages,clips,script,save]);
 useEffect(()=>()=>{clearTimeout(timer.current);const value=latest.current;void fetch(`/api/projects/${initial.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(value),keepalive:true}).catch(()=>{});},[initial.id]);
 useEffect(()=>{const frame=requestAnimationFrame(()=>{const box=chatMessagesRef.current;if(box)box.scrollTop=box.scrollHeight;else chatEnd.current?.scrollIntoView({block:'nearest'});});return()=>cancelAnimationFrame(frame);},[messages,jobs,production.production?.events.length]);
 useEffect(()=>{const raw=sessionStorage.getItem(`draft-${initial.id}`);if(raw){try{const value=JSON.parse(raw) as ComposerValue;draft.current=value;setSeedPrompt(typeof value.prompt==='string'?value.prompt:'');}catch{}sessionStorage.removeItem(`draft-${initial.id}`);}},[initial.id]);
 const checkpoint=()=>{setHistory(h=>[...h,{nodes:structuredClone(nodesRef.current),edges:structuredClone(edgesRef.current),layout:structuredClone(productionLayout)}].slice(-50));setFuture([]);};
 const workflowPosition=(index:number,origin:{x:number;y:number})=>({x:origin.x+(index%3)*300,y:origin.y+Math.floor(index/3)*250});
 const createWorkflowNode=(item:WorkflowNodeAction,index:number,origin:{x:number;y:number}):Node<CanvasNode['data']>=>({id:crypto.randomUUID(),type:'studio',position:workflowPosition(index,origin),data:{kind:item.kind||'文本',title:item.title||`${item.kind||'文本'} ${index+1}`,text:item.text||'',...(typeof item.duration==='number'?{duration:item.duration}:{})}});
 const applyWorkflow=(workflow?:WorkflowResult)=>{
  if(!workflow?.actions?.length)return false;
  const nextNodes=structuredClone(nodesRef.current);const nextEdges=structuredClone(edgesRef.current);const origin=rf.screenToFlowPosition({x:window.innerWidth*(chat?.38:.5),y:150});let scriptValue=scriptRef.current;let focusKind='';
  const append=(items:WorkflowNodeAction[],connect=false)=>{
   const added=items.map((item,index)=>createWorkflowNode(item,nextNodes.length+index,origin));nextNodes.push(...added);
   if(connect)for(let index=1;index<added.length;index++)nextEdges.push({id:crypto.randomUUID(),source:added[index-1].id,target:added[index].id});
  };
  const ensureScriptNode=()=>{
   const current=nextNodes.find(node=>node.data.kind==='剧本');
   if(current)current.data={...current.data,text:scriptValue,title:current.data.title||'项目剧本'};
   else append([{kind:'剧本',title:'项目剧本',text:scriptValue}]);
  };
  for(const action of workflow.actions){
   if(action.type==='create_node')append([action]);
   else if(action.type==='create_nodes')append(action.nodes,true);
   else if(action.type==='replace_script'){scriptValue=action.script;ensureScriptNode();}
   else if(action.type==='split_storyboard'){
    scriptValue=action.script;ensureScriptNode();
    const blocks=action.script.split(/\n\s*\n|(?=^镜头\s*\d)|(?=^场\s*\d)/m).map(value=>value.trim()).filter(Boolean).slice(0,100);
    append(blocks.map((text,index)=>({kind:'分镜',title:`镜头 ${index+1}`,text,duration:5})),true);focusKind='分镜';
   }else if(action.type==='focus')focusKind=action.kind;
  }
  nodesRef.current=nextNodes;edgesRef.current=nextEdges;scriptRef.current=scriptValue;setNodes(nextNodes);setEdges(nextEdges);setScript(scriptValue);
  if(focusKind)setTimeout(()=>{const related=nextNodes.filter(node=>node.data.kind===focusKind);if(related.length)void rf.fitView({nodes:related,padding:.25,duration:450});},60);
  notify('已根据对话同步画布');
  return true;
 };
 const undo=()=>{if(!history.length)return;const prev=history.at(-1)!;setFuture(f=>[...f,{nodes:structuredClone(nodes),edges:structuredClone(edges),layout:structuredClone(productionLayout)}]);setNodes(prev.nodes);setEdges(prev.edges);setProductionLayout(prev.layout);setHistory(h=>h.slice(0,-1));};
 const redo=()=>{if(!future.length)return;const next=future.at(-1)!;setHistory(h=>[...h,{nodes:structuredClone(nodes),edges:structuredClone(edges),layout:structuredClone(productionLayout)}]);setNodes(next.nodes);setEdges(next.edges);setProductionLayout(next.layout);setFuture(f=>f.slice(0,-1));};
 const addNode=(kind:string,asset?:Asset,screen?:{x:number;y:number})=>{checkpoint();const pos=rf.screenToFlowPosition(screen||{x:window.innerWidth*.59,y:window.innerHeight*.38});const node:CanvasNode={id:crypto.randomUUID(),type:'studio',position:{x:pos.x+nodes.length%3*25,y:pos.y+nodes.length%3*25},data:{kind,title:asset?.name||`${kind} ${nodes.filter(n=>n.data.kind===kind).length+1}`,text:'',...(asset?{url:asset.url,mime:asset.mime}:{}),...(['分镜','视频'].includes(kind)?{duration:5}:{}),...(['图片','视频'].includes(kind)?{ratio:'16:9',resolution:kind==='图片'?'2K':'720p'}:{})}};setNodes(v=>[...v,node as Node<CanvasNode['data']>]);setShowAdd(false);setMenuPosition(null);if(!asset)setInspector(node.id);};
 const openAddMenu=(screen:{x:number;y:number})=>{setMenuPosition(screen);setShowAdd(true);};
 const remove=(id:string)=>{checkpoint();setNodes(n=>n.filter(v=>v.id!==id));setEdges(e=>e.filter(v=>v.source!==id&&v.target!==id));setInspector('');};
 const duplicate=(id:string)=>{const node=nodes.find(n=>n.id===id);if(!node)return;checkpoint();setNodes(n=>[...n,{...structuredClone(node),id:crypto.randomUUID(),position:{x:node.position.x+40,y:node.position.y+40},selected:false,data:{...node.data,title:`${node.data.title} 副本`}}]);};
 const editNode=(changes:Partial<CanvasNode['data']>)=>setNodes(n=>n.map(v=>v.id===inspector?{...v,data:{...v.data,...changes}}:v));
 const uploadFiles=async(files:File[],screen?:{x:number;y:number})=>{if(!files.length)return;const form=new FormData();files.forEach(f=>form.append('files',f));form.append('category','其他');try{const {assets}=await api<{assets:Asset[]}>('/assets/upload',{method:'POST',body:form});checkpoint();const pos=rf.screenToFlowPosition(screen||{x:window.innerWidth*.55,y:200});setNodes(n=>[...n,...assets.map((a,i)=>({id:crypto.randomUUID(),type:'studio',position:{x:pos.x+i*330,y:pos.y},data:{kind:a.mime.startsWith('image/')?'图片':a.mime.startsWith('video/')?'视频':'音频',title:a.name,text:'',url:a.url,mime:a.mime}}))]);await refresh();notify(`已添加 ${assets.length} 个素材`);}catch(e){notify((e as Error).message,true);}};
 const switchToProduction=async()=>{try{const updated=await patch<Project>(`/projects/${initial.id}`,{category:'剧情故事创作'});setCategory(updated.category);setName(updated.name);notify('已切换为制作流程，原自由画布内容仍保留。');}catch(e){notify((e as Error).message,true);}};
 const appendMessage=(message:Message)=>{const next=[...messagesRef.current,message];messagesRef.current=next;setMessages(next);};
 const buildCanvasContext=(sourceId?:string)=>({selectedNodeId:sourceId||'',nodes:nodesRef.current.slice(0,120).map(node=>({id:node.id,kind:node.data.kind,title:node.data.title,text:node.data.text.slice(0,1200),url:node.data.url||'',position:node.position})),script:scriptRef.current.slice(0,16000),recentMessages:messagesRef.current.slice(-12).map(message=>({role:message.role,text:message.text.slice(0,1200)}))});
 const buildJobSettings=(v:ComposerValue,override?:Record<string,unknown>,sourceId?:string)=>{const source=nodesRef.current.find(node=>node.id===sourceId);const settings=override||{style:v.style,skill:v.skill,ratio:v.ratio,resolution:v.resolution,duration:v.duration,assets:[...v.assets.map(asset=>asset.url),...(source?.data.url?[source.data.url]:[])],references:[...v.assets.filter(asset=>asset.mime.startsWith('image/')).map(asset=>asset.url),...(source?.data.mime?.startsWith('image/')&&source.data.url?[source.data.url]:[])]};const linked={...settings,...(source?{sourceNodeId:source.id,sourceTitle:source.data.title,sourceText:source.data.text,sourceUrl:source.data.url||''}:{})};return v.kind==='Agent'?{...linked,workflow:true,canvasContext:buildCanvasContext(sourceId)}:linked;};
 const applyJobResult=(current:Job,v:ComposerValue,sourceId?:string,targetId?:string)=>{
  if(current.workflow?.actions?.length||current.outputUrl)checkpoint();
  applyWorkflow(current.workflow);
  if(current.outputUrl){
   if(targetId&&nodesRef.current.some(node=>node.id===targetId)){const next=nodesRef.current.map(node=>node.id===targetId?{...node,data:{...node.data,url:current.outputUrl,mime:v.kind==='视频'?'video/mp4':v.kind==='音频'?'audio/mpeg':'image/png'}}:node);nodesRef.current=next;setNodes(next);notify('生成结果已填入画框');return;}
   const source=nodesRef.current.find(node=>node.id===sourceId);const id=crypto.randomUUID();
   const next=[...nodesRef.current,{id,type:'studio',position:source?{x:source.position.x+320,y:source.position.y+70}:{x:(nodesRef.current.length%3)*340,y:Math.floor(nodesRef.current.length/3)*360},data:{title:source?`${source.data.title} · 生成结果`:'生成结果',kind:v.kind==='Agent'?'图片':v.kind,text:current.text||'',url:current.outputUrl,mime:v.kind==='视频'?'video/mp4':v.kind==='音频'?'audio/mpeg':'image/png'}} as Node<CanvasNode['data']>];
   nodesRef.current=next;setNodes(next);if(source)setEdges(current=>[...current,{id:crypto.randomUUID(),source:source.id,target:id}]);notify('生成结果已添加到画布');
  }
 };
 const runJob=async(v:ComposerValue,includeUser=true,settingsOverride?:Record<string,unknown>,sourceId?:string,targetId?:string)=>{
  const now=new Date().toISOString();if(includeUser)appendMessage({id:crypto.randomUUID(),role:'user',text:v.prompt,createdAt:now});setSeedPrompt('');setPendingJobs(count=>count+1);
  try{
   const job=await post<Job>('/generate',{projectId:initial.id,prompt:v.prompt,kind:v.kind,model:v.model,settings:{...buildJobSettings(v,settingsOverride,sourceId),...(targetId?{targetNodeId:targetId}:{})}});setJobs(j=>[job,...j]);
   if(job.status==='blocked'){appendMessage({id:crypto.randomUUID(),role:'system',text:job.error||'生成服务尚未配置。',createdAt:new Date().toISOString()});return;}
   const poll=async()=>{
    const current=await api<Job>(`/jobs/${job.id}`);setJobs(j=>j.map(item=>item.id===job.id?current:item));
    if(current.status==='running'||current.status==='queued')return false;
    if(current.status==='completed'){applyJobResult(current,v,sourceId,targetId);appendMessage({id:crypto.randomUUID(),role:'assistant',text:current.text||'生成完成，结果已添加到画布。',createdAt:new Date().toISOString(),...(current.workflow?{workflow:current.workflow}:{})});}
    else appendMessage({id:crypto.randomUUID(),role:'system',text:current.error||'任务已取消',createdAt:new Date().toISOString()});
    return true;
   };
   let done=await poll();while(!done){await new Promise(resolve=>setTimeout(resolve,1800));done=await poll();}
  }catch(error){notify((error as Error).message,true);}finally{setPendingJobs(count=>Math.max(0,count-1));}
 };
 const send=async(v:ComposerValue)=>{const source=sourceNodeId;setSourceNodeId('');await runJob(v,true,undefined,source);};
 const retryJob=async(job:Job)=>{
  const kind=['Agent','图片','视频','音频'].includes(job.kind)?job.kind:'Agent';const settings=job.settings||{};const value:ComposerValue={prompt:job.prompt,model:job.model,kind,style:typeof settings.style==='string'?settings.style:'',skill:typeof settings.skill==='string'?settings.skill:'',assets:[],ratio:typeof settings.ratio==='string'?settings.ratio:'16:9',resolution:typeof settings.resolution==='string'?settings.resolution:(kind==='图片'?'2K':'720p'),duration:Number(settings.duration)||5};await runJob(value,false,settings,typeof settings.sourceNodeId==='string'?settings.sourceNodeId:undefined,typeof settings.targetNodeId==='string'?settings.targetNodeId:undefined);
 };
 const sendQuickReply=(text:string)=>{void send({prompt:text,model:'Agent',kind:'Agent',style:'',skill:'',assets:[],ratio:'16:9',resolution:'720p',duration:5});};
 const selected=nodes.find(n=>n.id===inspector);
 const selectedMedia=selected&&['图片','视频','音频'].includes(selected.data.kind);
 const configuredFrameModels=data.agentSources.filter(source=>source.enabled&&source.apiKeyConfigured&&source.kind===(selected?.data.kind==='图片'?'图文':selected?.data.kind)).flatMap(source=>source.models);
 const frameModels=configuredFrameModels.length?configuredFrameModels:data.provider.configured?modelGroups[selected?.data.kind||'图片']||[]:[];
 const frameBusy=Boolean(selected&&jobs.some(job=>['running','queued'].includes(job.status)&&job.settings?.targetNodeId===selected.id));
 const selectedFrameSource=data.agentSources.find(source=>source.enabled&&source.apiKeyConfigured&&source.kind===(selected?.data.kind==='图片'?'图文':selected?.data.kind)&&source.models.some(model=>model.name===(selected?.data.model||frameModels[0]?.name)));
 const frameReferencesSupported=!selectedFrameSource||['generic','openai-video'].includes(selectedFrameSource.adapter||'generic');const lastFrameSupported=!selectedFrameSource||selectedFrameSource.adapter==='generic'||(selected?.data.model||frameModels[0]?.name||'').startsWith('agnes-video-2.5');
 const generateFrame=(node:Node<CanvasNode['data']>)=>{const model=node.data.model||frameModels[0]?.name;if(!node.data.text.trim()){notify('请先填写提示词',true);return;}if(!model){notify('请先配置对应的生成模型',true);return;}const value:ComposerValue={prompt:node.data.text,model,kind:node.data.kind,style:node.data.style||'',skill:'',assets:[],ratio:node.data.ratio||'16:9',resolution:node.data.resolution||(node.data.kind==='图片'?'2K':'720p'),duration:node.data.duration||5};const settings={style:value.style,skill:'',ratio:value.ratio,resolution:value.resolution,duration:value.duration,assets:[node.data.firstFrameUrl,node.data.lastFrameUrl].filter(Boolean),firstFrameUrl:node.data.firstFrameUrl||'',lastFrameUrl:node.data.lastFrameUrl||''};void runJob(value,false,settings,node.id,node.id);};
 const productionOffset=nodes.length?Math.max(...nodes.map(node=>node.position.y))+520:0;
 const productionCanvasNodes=useMemo(()=>productionNodes(production.production,{x:productionMode?470:0,y:productionOffset}).map(node=>({...node,position:productionLayout[node.id]||node.position,data:{...node.data,...(node.data.item?{cardColor:productionCardColors[node.data.item.id]||'white'}:{})}})),[production.production,productionMode,productionOffset,productionLayout,productionCardColors]);
 const canvasNodes:DisplayNode[]=useMemo(()=>[...nodes,...productionCanvasNodes],[nodes,productionCanvasNodes]);
 canvasNodesRef.current=canvasNodes;
 const layoutProductionRoles=(layout:'vertical'|'horizontal'|'connected')=>{const roles=productionCanvasNodes.filter(node=>node.type==='production'&&node.data.kind==='角色').sort((a,b)=>a.position.y-b.position.y||a.position.x-b.position.x);if(!roles.length)return;const left=Math.min(...roles.map(node=>node.position.x)),top=Math.min(...roles.map(node=>node.position.y));const next:Record<string,{x:number;y:number}>={};if(layout==='vertical'){let y=top;for(const node of roles){next[node.id]={x:left,y};y+=node.height+48;}}else if(layout==='horizontal'){let x=left;for(const node of roles){next[node.id]={x,y:top};x+=node.width+48;}}else{const columns=Math.ceil(Math.sqrt(roles.length));const colWidths=Array(columns).fill(0) as number[];roles.forEach((node,index)=>{const col=index%columns;colWidths[col]=Math.max(colWidths[col],node.width);});const rowHeights=Array(Math.ceil(roles.length/columns)).fill(0) as number[];roles.forEach((node,index)=>{const row=Math.floor(index/columns);rowHeights[row]=Math.max(rowHeights[row],node.height);});const colX:number[]=[];const rowY:number[]=[];for(let i=0;i<columns;i++)colX[i]=left+(i?colX[i-1]+colWidths[i-1]+48:0);for(let i=0;i<rowHeights.length;i++)rowY[i]=top+(i?rowY[i-1]+rowHeights[i-1]+48:0);roles.forEach((node,index)=>{next[node.id]={x:colX[index%columns],y:rowY[Math.floor(index/columns)]};});}setProductionLayout(current=>({...current,...next}));};
 const stageFocus=useRef('');
 useEffect(()=>{if(!productionMode||!production.production)return;const key=`${production.production.stage}:${production.production.status}`;if(stageFocus.current===key)return;stageFocus.current=key;const target=production.production.stage==='videos'?productionCanvasNodes.find(node=>node.data.kind==='分镜'&&node.data.item&&!node.data.item.videoUrl):productionCanvasNodes.find(node=>node.data.kind==='分镜')||productionCanvasNodes.find(node=>node.data.kind==='剧本');if(!target)return;const timer=setTimeout(()=>canvasFit(tldrawEditor.current,[target],.3),160);return()=>clearTimeout(timer);},[productionMode,production.production?.stage,production.production?.status,productionCanvasNodes]);
 const productionContext={
  inspect:(id:string,slot='imageUrl')=>{const role=production.production?.characters.find(item=>item.id===id);if(role){setCharacterSelection({id,slot});setProductionDetail('');setChat(false);setPan(false);return;}setCharacterSelection(null);setProductionDetail(id);const nodeId=id==='script'?'production-script':id.startsWith('production-')?id:`production-${id}`;const target=canvasNodes.find(node=>node.id===nodeId);if(target)void rf.fitView({nodes:[target],padding:.42,duration:450});},
  preview:(url:string,kind:string)=>setMediaPreview({url,kind}),
  replace:(id:string,slot:string)=>{open('asset-picker',{select:(asset:Asset)=>{void production.command({action:'replace_asset',targetId:id,assetSlot:slot,assetUrl:asset.url});}});},
 };
 useEffect(()=>{
  const stage=production.production?.stage;
  if(!productionMode||!stage||production.production?.status==='idle')return;
  const kinds=stage==='script'?['剧本']:stage==='design'||stage==='design_images'?['角色','场景']:['storyboard','storyboard_images','video_prompts','videos'].includes(stage)?['分镜']:stage==='music'?['音乐']:['成片'];
  const related=canvasNodes.filter(node=>node.type==='production'&&kinds.includes(String(node.data.kind)));
  if(related.length&&related.length<=8){const timer=setTimeout(()=>void rf.fitView({nodes:related,padding:.3,duration:450}),80);return()=>clearTimeout(timer);}
 },[productionMode,production.production?.stage,production.production?.status,production.production?.version]);
 const section=(kind:string)=>{if(kind==='总览'){void rf.fitView({nodes:canvasNodes,padding:.25,duration:400});return;}const related=canvasNodes.filter(n=>n.data.kind===kind);if(related.length)void rf.fitView({nodes:related,padding:.25,duration:400});else if(productionMode)return;else if(kind==='剧本')setShowScript(true);else addNode(kind);};
 const handleSend=async(v:ComposerValue)=>{if(productionMode){await production.send(v,data.agentSources);return;}await send(v);};
 const productionBusy=!production.ready||production.submitting||production.production?.status==='running';
 useEffect(()=>{const shortcut=(event:KeyboardEvent)=>{const target=event.target as HTMLElement;if(target.closest('input,textarea,select,[contenteditable="true"]'))return;if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='z'){event.preventDefault();if(event.shiftKey)redo();else undo();}else if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='s'){event.preventDefault();void save().catch(()=>{});}};window.addEventListener('keydown',shortcut);return()=>window.removeEventListener('keydown',shortcut);},[history,future,nodes,edges,productionLayout,save]);
 return <ProductionProvider value={productionContext}><NodeContext.Provider value={{edit:id=>{checkpoint();setInspector(id);},remove,duplicate,connect:id=>{setConnectingFrom(id);notify('请点击要连接的目标节点');}}}><div className={`editor-shell ${chat?'with-chat':''} ${productionMode?'production-shell':''}`} onDoubleClickCapture={e=>{if(!productionMode&&(e.target as HTMLElement).closest('.workbench-tldraw') && !(e.target as HTMLElement).closest('.workbench-shape'))openAddMenu({x:e.clientX,y:e.clientY});}} onContextMenuCapture={e=>{if(!productionMode&&(e.target as HTMLElement).closest('.workbench-tldraw') && !(e.target as HTMLElement).closest('.workbench-shape')){e.preventDefault();openAddMenu({x:e.clientX,y:e.clientY});}}}>
 <TldrawCanvas minimap={minimap} onDuplicate={duplicate} onCheckpoint={checkpoint} nodes={canvasNodes} edges={edges} onDelete={remove} editorRef={tldrawEditor} pan={pan} onSelect={id=>{const target=canvasNodes.find(n=>n.id===id);if(!target)return;if(target.type==='production'){const item=target.data as ProductionNodeData;if(item.kind==='角色'&&item.item){setCharacterSelection({id:String(item.item.id),slot:'card'});setProductionDetail('');setChat(false);setPan(false);}else if(!item.section)productionContext.inspect(item.kind==='剧本'?'script':String(item.item?.id||''));}else if(connectingFrom&&connectingFrom!==id){checkpoint();setEdges(current=>current.some(edge=>edge.source===connectingFrom&&edge.target===id)?current:[...current,{id:crypto.randomUUID(),source:connectingFrom,target:id}]);setConnectingFrom('');notify('节点已连接');}else setInspector(id);}} onPane={()=>{setInspector('');setShowAdd(false);}} onPosition={(id,x,y)=>{if(id.startsWith('production-')){setProductionLayout(current=>({...current,[id]:{x,y}}));return;}if(!nodesRef.current.some(n=>n.id===id))return;setNodes(current=>current.map(n=>n.id===id?{...n,position:{x,y}}:n));}} renderStudio={(id,data)=><StudioNode id={id} data={data} selected={inspector===id}/>} onDrop={(files,point)=>void uploadFiles(files,point)}/>
 <div className="editor-top-left"><Link to="/project" className="editor-brand">Oii<ChevronDown size={12}/></Link><button className="editor-name" onClick={()=>open('text-form',{title:'重命名项目',label:'项目名称',initial:name,submit:async(value:string)=>setName(value)})}>{name}</button><IconButton label="导出项目" onClick={()=>downloadJson({...projectRef.current,...latest.current},`${name}.json`)}><Share2 size={17}/></IconButton><IconButton label="保存项目" onClick={()=>void save().catch(()=>{})}><Save size={17}/></IconButton></div>
 {productionMode&&<div className="editor-navigation">{['总览','剧本','角色','场景','分镜'].map(k=><button key={k} onClick={()=>section(k)}>{k}</button>)}{production.production?.stage==='videos'&&production.production.shots.find(shot=>!shot.videoUrl)&&<button className="pending-shot-jump" onClick={()=>{const target=productionCanvasNodes.find(node=>node.data.kind==='分镜'&&node.data.item&&!node.data.item.videoUrl);if(target)canvasFit(tldrawEditor.current,[target],.3);}}>待生成镜头 {production.production.shots.find(shot=>!shot.videoUrl)?.number}</button>}</div>}<div className="editor-top-right"><span className={`save-status ${saveState==='保存失败'?'danger-text':''}`}>{saveState==='已保存'?<Check size={13}/>:<span className="save-dot"/>}{saveState}</span><button className="button subtle" onClick={()=>{setClips(c=>c.length?c:nodes.filter(n=>n.data.url).map(n=>({id:crypto.randomUUID(),url:n.data.url!,title:n.data.title,mime:n.data.mime||'image/png',duration:n.data.duration||5,start:0,muted:false})));setShowTimeline(true);}}><Clapperboard size={15}/>去剪辑</button><button className="button subtle" onClick={()=>open('publish')}><Send size={14}/>发布</button></div>
 {chat?<aside className={`editor-chat ${productionMode?'production-chat':''} ${historyOpen?'show-history':''}`}>
  <div className="chat-tabs">
   {productionMode?
    <><span className="production-agent-pill"><span className="agent-pin"/>Oii Agent</span><span className="production-chat-state">{productionBusy?'批量生成…':production.production?.stage==='script'?'制作流程':'制作对话'}</span><IconButton label="更多对话操作"><MoreHorizontal size={16}/></IconButton><IconButton label="对话设置" onClick={()=>open('settings')}><Settings size={15}/></IconButton></>:
    <><span><span className="agent-pin"/>Oii Agent</span><button onClick={()=>setShowTasks(true)}>任务记录</button></>}
   <IconButton label="收起聊天" onClick={()=>setChat(false)}><PanelLeftClose size={16}/></IconButton>
  </div>
  <div className="chat-messages" ref={chatMessagesRef}>
   {!productionMode&&!messages.length&&<div className="chat-welcome"><img src="/assets/director.png" alt=""/><h2>一起，把想象变成作品</h2><p>你的创作从这里开始</p><div>{['编写剧本','角色设计','制作分镜'].map(t=><button key={t} onClick={()=>setSeedPrompt(t)}>{t}</button>)}</div></div>}
   {!productionMode&&messages.map(m=><div key={m.id} className={`message ${m.role}`}>{m.role==='assistant'&&<div className="agent-label"><img src="/assets/writer.png" alt=""/>Oii Agent</div>}{m.role==='system'&&<AlertCircle size={17}/>}<div>{m.text}</div>{m.workflow?.quickReplies?.length&&<div className="quick-replies">{m.workflow.quickReplies.map(reply=><button key={reply} disabled={busy} onClick={()=>sendQuickReply(reply)}>{reply}</button>)}</div>}{m.role==='system'&&<button className="text-button" onClick={()=>open('settings')}>查看服务设置<ArrowLeft size={13} className="rotate"/></button>}</div>)}
   {busy&&!productionMode&&<div className="message system"><LoaderCircle size={17} className="spin"/>生成任务执行中…</div>}
   {productionMode&&<ProductionConversation controller={production} onInspect={productionContext.inspect}/>}
   <div ref={chatEnd}/>
  </div>
  {!productionMode&&<div className="free-chat-actions"><button onClick={()=>setHistoryOpen(!historyOpen)}><MessagesSquare size={15}/>{historyOpen?'收起记录':`创作记录${messages.length?` · ${messages.length}`:''}`}</button><button onClick={()=>void switchToProduction()}>制作流程</button></div>}
  {!productionMode&&sourceNodeId&&<div className="canvas-reference"><span>关联节点：{nodes.find(node=>node.id===sourceNodeId)?.data.title||'已删除节点'}</span><IconButton label="取消关联" onClick={()=>setSourceNodeId('')}><X size={14}/></IconButton></div>}
  <Composer compact initialPrompt={seedPrompt} initialSkill={productionMode?category:initial.category==='自由画布'?'':initial.category} onSubmit={v=>void handleSend(v)} busy={productionMode&&productionBusy}/>
 </aside>:<IconButton label="展开聊天" className="chat-expand" onClick={()=>setChat(true)}><PanelLeftOpen size={20}/></IconButton>}
 {!nodes.length&&!productionMode&&<div className="canvas-empty"><p><strong>✧ 双击或右键</strong> 在画布任意位置创建画框并开始生成</p><div className="canvas-starters"><button onClick={()=>uploadRef.current?.click()}><Upload size={19}/>上传</button><button className="starter-image" onClick={()=>addNode('图片')}><Image size={19}/>图片</button><button className="starter-video" onClick={()=>addNode('视频')}><Film size={19}/>视频</button><button className="starter-asset" onClick={()=>open('asset-picker',{select:(a:Asset)=>addNode(a.mime.startsWith('image/')?'图片':a.mime.startsWith('video/')?'视频':'音频',a)})}><Folder size={19}/>添加资产</button><button className="starter-stage" onClick={()=>navigate('/stage')}><Grid2X2 size={19}/>3D 导演台</button></div></div>}
 <div className="canvas-tools"><IconButton label="添加素材" className="primary" onClick={e=>{if(showAdd)setShowAdd(false);else openAddMenu(productionMode?{x:95,y:window.innerHeight-330}:{x:(e.currentTarget as HTMLElement).getBoundingClientRect().left-190,y:window.innerHeight*.43});}}><Plus size={21}/></IconButton><IconButton label="资产库" onClick={()=>open('asset-picker',{select:(a:Asset)=>addNode(a.mime.startsWith('image/')?'图片':a.mime.startsWith('video/')?'视频':'音频',a)})}><Folder size={19}/></IconButton><IconButton label="选择工具" className={!pan?'active':''} onClick={()=>setPan(false)}><MousePointer2 size={18}/></IconButton><IconButton label="移动画布" className={pan?'active':''} onClick={()=>setPan(true)}><Hand size={18}/></IconButton><div className="tool-divider"/><IconButton label="撤销" disabled={!history.length} onClick={undo}><Undo2 size={18}/></IconButton><IconButton label="重做" disabled={!future.length} onClick={redo}><Redo2 size={18}/></IconButton><IconButton label="小地图" className={minimap?'active':''} onClick={()=>setMinimap(!minimap)}><Map size={18}/></IconButton></div>
 {connectingFrom&&<div className="canvas-connect-hint">点击目标节点以连接 <button onClick={()=>setConnectingFrom('')}>取消</button></div>}
 {showAdd&&<div className="canvas-add-menu" style={menuPosition?{left:Math.max(8,Math.min(window.innerWidth-200,menuPosition.x)),top:Math.max(72,Math.min(window.innerHeight-360,menuPosition.y)),bottom:'auto'}:undefined}>{(productionMode?[['文本',Type],['剧本',FileText],['图片',Image],['视频',Film],['角色',Sparkles],['场景',Grid2X2],['分镜',Clapperboard]]:[['图片',Image],['视频',Film],['音频',Music],['文本',Type]]).map(([label,Icon]:any)=><button key={label} onClick={()=>addNode(label,undefined,menuPosition||undefined)}><Icon size={17}/>{label}</button>)}{!productionMode&&<><button onClick={()=>{setShowAdd(false);navigate('/stage');}}><Grid2X2 size={17}/>3D 导演台</button><button onClick={()=>open('asset-picker',{select:(a:Asset)=>addNode(a.mime.startsWith('image/')?'图片':a.mime.startsWith('video/')?'视频':'音频',a,menuPosition||undefined)})}><Folder size={17}/>添加资产</button></>}<button onClick={()=>uploadRef.current?.click()}><Upload size={17}/>上传素材</button></div>}
 <input hidden ref={uploadRef} type="file" multiple accept="image/*,video/*,audio/*" onChange={e=>{void uploadFiles(Array.from(e.target.files||[]),menuPosition||undefined);setShowAdd(false);e.target.value='';}}/>
 <button className="task-status" onClick={()=>setShowTasks(!showTasks)}><span>{busy?<LoaderCircle size={20} className="spin"/>:<Check size={20}/>}</span><div><b>任务列表</b><small>{busy?`${pendingJobs} 个任务执行中`:jobs.length?`${jobs.length} 条任务记录`:'当前无任务'}</small></div><ChevronDown size={15}/></button>
 {showTasks&&<div className="task-panel"><header><h3>任务列表</h3><IconButton label="关闭任务列表" onClick={()=>setShowTasks(false)}><X size={16}/></IconButton></header>{!jobs.length?<Empty title="当前无任务"/>:jobs.map(j=><article key={j.id}><strong>{j.model}</strong><span className={`job-status ${j.status}`}>{{blocked:'未配置',running:'生成中',completed:'已完成',failed:'失败',cancelled:'已取消',queued:'排队中'}[j.status]||j.status}</span><p>{j.prompt}</p>{j.error&&<small>{j.error}</small>}<div className="task-actions">{j.status==='running'&&<button className="button small" onClick={async()=>{const updated=await post<Job>(`/jobs/${j.id}/cancel`,{});setJobs(js=>js.map(x=>x.id===j.id?updated:x));}}>取消任务</button>}{['failed','cancelled'].includes(j.status)&&<button className="button small" disabled={busy} onClick={()=>void retryJob(j)}><Redo2 size={13}/>重试</button>}</div></article>)}</div>}
 {selected&&<aside className="node-inspector">
  <header><h3>{selected.data.kind}画框</h3><IconButton label="关闭属性面板" onClick={()=>setInspector('')}><X size={17}/></IconButton></header>
  <label className="form-field">名称<input value={selected.data.title} maxLength={160} onFocus={checkpoint} onChange={e=>editNode({title:e.target.value})}/></label>
  <label className="form-field">{selectedMedia?'提示词':'内容 / 提示词'}<textarea rows={selectedMedia?5:8} value={selected.data.text} onFocus={checkpoint} onChange={e=>editNode({text:e.target.value})}/></label>
  {selectedMedia&&<>
   <label className="form-field">模型<select value={selected.data.model||frameModels[0]?.name||''} onChange={e=>{checkpoint();editNode({model:e.target.value});}}>{frameModels.length?frameModels.map(model=><option key={model.name} value={model.name}>{model.name}</option>):<option value="">尚未配置模型</option>}</select></label>
   {selected.data.kind!=='音频'&&<><label className="form-field">风格<input value={selected.data.style||''} onFocus={checkpoint} onChange={e=>editNode({style:e.target.value})} placeholder="可选"/></label><label className="form-field">画面比例<select value={selected.data.ratio||'16:9'} onChange={e=>{checkpoint();editNode({ratio:e.target.value});}}>{['16:9','9:16','1:1','4:3','3:4'].map(value=><option key={value}>{value}</option>)}</select></label><label className="form-field">清晰度<select value={selected.data.resolution||(selected.data.kind==='图片'?'2K':'720p')} onChange={e=>{checkpoint();editNode({resolution:e.target.value});}}>{(selected.data.kind==='图片'?['1K','2K','4K']:['480p','720p','1080p']).map(value=><option key={value}>{value}</option>)}</select></label></>}
   {selected.data.kind==='视频'&&<label className="form-field">时长（秒）<select value={selected.data.duration||5} onChange={e=>{checkpoint();editNode({duration:Number(e.target.value)});}}>{[5,10,15,30].map(value=><option value={value} key={value}>{value} 秒</option>)}</select></label>}
   {selected.data.kind==='视频'&&frameReferencesSupported&&<div className="frame-reference-fields">{([['首帧','firstFrameUrl'],['尾帧','lastFrameUrl']] as const).filter(([,key])=>key==='firstFrameUrl'||lastFrameSupported).map(([label,key])=><div key={key}><span>{label}</span>{selected.data[key]&&<img src={selected.data[key]} alt={`${label}参考图`}/>}<button className="button small" onClick={()=>open('asset-picker',{select:(asset:Asset)=>{if(!asset.mime.startsWith('image/')){notify('请选择图片素材',true);return;}checkpoint();editNode({[key]:asset.url});}})}>{selected.data[key]?'替换':'选择图片'}</button>{selected.data[key]&&<IconButton label={`清除${label}`} onClick={()=>{checkpoint();editNode({[key]:''});}}><X size={13}/></IconButton>}</div>)}</div>}
   {selected.data.kind==='视频'&&!frameReferencesSupported&&<p className="frame-reference-hint">当前数据源不支持首尾帧参数</p>}
   <button className="button primary full" disabled={!selected.data.text.trim()||!frameModels.length||frameBusy} onClick={()=>generateFrame(selected)}>{frameBusy?<LoaderCircle size={16} className="spin"/>:<Sparkles size={16}/>}生成{selected.data.kind}</button>
   {!frameModels.length&&<button className="text-button" onClick={()=>navigate('/agent-config')}>配置生成模型</button>}
  </>}
  {selected.data.kind==='分镜'&&<label className="form-field">时长（秒）<input type="number" min={1} max={300} value={selected.data.duration||5} onFocus={checkpoint} onChange={e=>editNode({duration:Math.max(1,Number(e.target.value)||1)})}/></label>}
  <button className="button full" onClick={()=>open('asset-picker',{select:(a:Asset)=>{checkpoint();editNode({url:a.url,mime:a.mime});}})}><Image size={16}/>选择素材</button>
  <button className="button full" onClick={()=>{setSourceNodeId(selected.id);setChat(true);setSeedPrompt(`基于「${selected.data.title}」继续创作：`);setInspector('');}}><Sparkles size={16}/>基于此节点继续创作</button>
  <div className="modal-actions"><IconButton label="复制节点" onClick={()=>duplicate(selected.id)}><Copy size={17}/></IconButton><IconButton label="删除节点" onClick={()=>remove(selected.id)}><Trash2 size={17}/></IconButton><button className="button primary" onClick={()=>{void save().catch(()=>{});setInspector('');}}>完成</button></div>
 </aside>}
 {showScript&&<Modal title="剧本与分镜" wide onClose={()=>setShowScript(false)}><label className="form-field">剧本<textarea rows={16} value={script} onChange={e=>setScript(e.target.value)} placeholder="输入或粘贴剧本，用空行分隔场次。"/></label><div className="modal-actions"><button className="button" onClick={()=>{const node:CanvasNode={id:crypto.randomUUID(),type:'studio',position:{x:0,y:0},data:{kind:'剧本',title:'我的剧本',text:script}};checkpoint();setNodes(n=>[...n,node as Node<CanvasNode['data']>]);setShowScript(false);}}>添加到画布</button><button className="button primary" disabled={!script.trim()} onClick={async()=>{try{await save();const p=await post<Project>(`/projects/${initial.id}/storyboard`,{script});checkpoint();setNodes(p.nodes as Node<CanvasNode['data']>[]);setEdges(p.edges);setShowScript(false);notify('已按场次拆分为可编辑分镜');setTimeout(()=>void rf.fitView({padding:.3}),100);}catch(e){notify((e as Error).message,true);}}}>按场次拆分分镜</button></div></Modal>}
 {showTimeline&&<Timeline projectId={initial.id} clips={clips} onChange={setClips} onClose={()=>setShowTimeline(false)} save={save}/>}
 {production.production&&characterSelection&&production.production.characters.find(item=>item.id===characterSelection.id)&&<CharacterPopover key={`${characterSelection.id}:${characterSelection.slot}`} p={production.production} item={production.production.characters.find(item=>item.id===characterSelection.id)!} slot={characterSelection.slot} cardColor={productionCardColors[characterSelection.id]||'white'} onLayout={layoutProductionRoles} onColor={color=>setProductionCardColors(current=>({...current,[characterSelection.id]:color}))} command={production.command} accept={production.accept} editorRef={tldrawEditor} onClose={()=>{setCharacterSelection(null);setChat(true);}} onPreview={url=>setMediaPreview({url,kind:'image'})}/>}
 {production.production&&productionDetail&&<ProductionInspector p={production.production} id={productionDetail} command={production.command} onClose={()=>setProductionDetail('')}/>}
 {mediaPreview?.kind==='image'&&<ImageLightbox url={mediaPreview.url} onClose={()=>setMediaPreview(null)}/>}
 {mediaPreview&&mediaPreview.kind!=='image'&&<Modal title={mediaPreview.kind==='video'?'视频预览':mediaPreview.kind==='audio'?'音频预览':'图片预览'} wide className="media-preview-modal" onClose={()=>setMediaPreview(null)}><div className="production-detail-media">{mediaPreview.kind==='video'?<video src={mediaPreview.url} controls autoPlay/>:mediaPreview.kind==='audio'?<audio src={mediaPreview.url} controls autoPlay/>:<img src={mediaPreview.url} alt="制作成果预览"/>}</div></Modal>}
 </div></NodeContext.Provider></ProductionProvider>;
}
