import { useState, useRef, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Plus, X, Search, Star, Check, Upload, Download, Trash2, Pencil, ArrowRight, Crown, Coins, Info, Settings, Zap, Play, Film, Copy, ChevronDown, RotateCcw, Mail, UserRound, LockKeyhole, LoaderCircle } from 'lucide-react';
import { useStudio } from './studio';
import { Modal, Tabs, SearchBox, IconButton, Empty, FileDrop } from './components';
import { api, post, patch, downloadJson } from './api';
import { styleNames, templates, industries } from './catalog';
import type { Asset, Skill, Work } from './types';

export function Overlays(){const{overlay,close}=useStudio();if(!overlay)return null;const{type,data}=overlay;let body;
 switch(type){
  case 'new-project':body=<NewProject/>;break;
  case 'text-form':body=<TextForm spec={data}/>;break;
  case 'confirm':body=<Confirm spec={data}/>;break;
  case 'styles':body=<StylePicker spec={data}/>;break;
  case 'templates':body=<TemplatePicker spec={data}/>;break;
  case 'asset-picker':body=<AssetPicker spec={data}/>;break;
  case 'asset-detail':body=<AssetDetail asset={data}/>;break;
  case 'skill-picker':body=<SkillPicker spec={data}/>;break;
  case 'skill-detail':body=<SkillDetail skill={data}/>;break;
  case 'create-skill':body=<SkillForm skill={data}/>;break;
  case 'work':body=<WorkDetail work={data}/>;break;
  case 'publish':body=<Publish spec={data}/>;break;
  case 'pricing':body=<Pricing/>;break;
  case 'settings':body=<SettingsPanel/>;break;
  case 'notifications':body=<Notifications/>;break;
  case 'balance':body=<Balance/>;break;
  case 'login':body=<Login spec={data}/>;break;
  default:body=<InfoPanel type={type}/>;
 }
 return body;
}
function Confirm({spec}:{spec:any}){const{close,notify}=useStudio();const[busy,setBusy]=useState(false);return <Modal title={spec.title} onClose={close}><p className="modal-copy">{spec.text}</p><div className="modal-actions"><button className="button" disabled={busy} onClick={close}>取消</button><button className={`button ${spec.danger?'danger':'primary'}`} disabled={busy} onClick={async()=>{setBusy(true);try{await spec.action();close();}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}}>{busy?'处理中…':'确认'}</button></div></Modal>;}
function TextForm({spec}:{spec:any}){const{close,notify}=useStudio();const[value,setValue]=useState(spec.initial||'');const[busy,setBusy]=useState(false);return <Modal title={spec.title} onClose={close}><form onSubmit={async e=>{e.preventDefault();if(!value.trim())return;setBusy(true);try{await spec.submit(value.trim());close();}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}}><label className="form-field">{spec.label}<input autoFocus required maxLength={160} value={value} onChange={e=>setValue(e.target.value)}/></label><div className="modal-actions"><button type="button" className="button" onClick={close}>取消</button><button className="button primary" disabled={busy||!value.trim()}>保存</button></div></form></Modal>;}
function NewProject(){const{close,createProject}=useStudio();const[name,setName]=useState('');const[category,setCategory]=useState('自由画布');const[busy,setBusy]=useState(false);return <Modal title="新建项目" onClose={close}><form onSubmit={async e=>{e.preventDefault();setBusy(true);await createProject(name.trim()||'未命名项目',category);setBusy(false);}}><label className="form-field">项目名称<input autoFocus placeholder="未命名项目" maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label className="form-field">创作类型<select value={category} onChange={e=>setCategory(e.target.value)}>{['自由画布','剧情故事创作','角色设计','场景设计','故事板做视频','爆款复刻'].map(v=><option key={v}>{v}</option>)}</select></label><div className="modal-actions"><button type="button" className="button" onClick={close}>取消</button><button className="button primary" disabled={busy}><Plus size={15}/>创建项目</button></div></form></Modal>;}
function StylePicker({spec}:{spec:any}){const{close,data,favorite,open}=useStudio();const[tab,setTab]=useState('全部风格');const[category,setCategory]=useState('全部');const[query,setQuery]=useState('');const list=styleNames.map((name,i)=>({name,id:`style-${i}`,image:`/assets/style-${i}.jpg`,i})).filter(s=>s.name.includes(query)&&(category==='全部'||s.name.includes(category)||(category==='漫剧'&&s.i%3===0))&&(tab!=='我的收藏'||data.favorites.includes(s.id))&&(tab!=='最近使用'||JSON.parse(localStorage.getItem('recent-styles')||'[]').includes(s.name))&&tab!=='我的风格');
 const select=(name:string)=>{const rec:string[]=JSON.parse(localStorage.getItem('recent-styles')||'[]');localStorage.setItem('recent-styles',JSON.stringify([name,...rec.filter(v=>v!==name)].slice(0,12)));spec?.select?.(name);close();};
 return <Modal title="风格" wide className="style-modal" onClose={close}><div className="modal-toolbar"><Tabs values={['全部风格','我的收藏','我的风格','最近使用']} value={tab} onChange={setTab}/><SearchBox value={query} onChange={setQuery} placeholder="搜索风格"/></div><Tabs values={['全部','漫剧','真人','3D','国风','2D','Q版','游戏','日系','欧美']} value={category} onChange={setCategory} pills/><div className="style-grid">{list.map(s=><article className="style-card" key={s.id}><button onClick={()=>select(s.name)}><img src={s.image} alt={s.name} onError={e=>{e.currentTarget.src=`/assets/skill-${s.i%17}.jpg`;e.currentTarget.onerror=null;}}/>{s.i<7&&<em>{s.i===0?'Hot':'New'}</em>}<strong>{s.name}</strong></button><IconButton label={`收藏 ${s.name}`} className="style-star" onClick={()=>void favorite(s.id)}><Star size={15} fill={data.favorites.includes(s.id)?'currentColor':'none'}/></IconButton><small>Oii 风格</small></article>)}</div>{!list.length&&<Empty title={tab==='我的风格'?'暂无自定义风格':'暂无符合条件的风格'}><button className="button" onClick={()=>open('asset-picker',{select:(a:Asset)=>select(a.name)})}>使用参考素材</button></Empty>}</Modal>;
}
function TemplatePicker({spec}:{spec:any}){const{close,notify}=useStudio();const[query,setQuery]=useState('');return <Modal title="提示词模板" wide onClose={close}><SearchBox value={query} onChange={setQuery} placeholder="搜索模板"/><div className="template-grid">{templates.filter(t=>t.name.includes(query)).map((t,i)=><article key={t.name}><img src={`/assets/skill-${i}.jpg`} alt=""/><div><small>{t.category}</small><h3>{t.name}</h3><p>{t.prompt}</p><button className="button" onClick={()=>{if(spec?.select){spec.select(t.prompt);close();}else{void navigator.clipboard.writeText(t.prompt).then(()=>notify('提示词已复制')).catch(()=>notify('复制失败',true));}}}>使用模板<ArrowRight size={15}/></button></div></article>)}</div></Modal>;}
function AssetDetail({asset}:{asset:Asset}){const{data,close,open,refresh,notify}=useStudio();const[name,setName]=useState(asset.name);const[category,setCategory]=useState(asset.category);const[description,setDescription]=useState(asset.description||'');const[busy,setBusy]=useState(false);const current=data.assets.find(a=>a.id===asset.id)||asset;return <Modal title="资产详情" wide className="asset-detail-modal" onClose={close}><div className="asset-detail-layout"><div className="asset-preview">{asset.mime.startsWith('image/')?<img src={asset.url} alt={name}/>:asset.mime.startsWith('video/')?<video src={asset.url} controls/>:<audio src={asset.url} controls/>}</div><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await patch(`/assets/${asset.id}`,{name,category,description});await refresh();notify('资产已保存');close();}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}}><label className="form-field">名称<input value={name} required onChange={e=>setName(e.target.value)}/></label><label className="form-field">分类<select value={category} onChange={e=>setCategory(e.target.value)}>{['角色','场景','道具','合集','其他'].map(v=><option key={v}>{v}</option>)}</select></label><label className="form-field">描述<textarea rows={5} value={description} onChange={e=>setDescription(e.target.value)}/></label><small className="muted">{asset.mime} · {(asset.size/1024/1024).toFixed(2)} MB</small><div className="modal-actions"><a className="button" href={asset.url} download={asset.name}><Download size={15}/></a><button type="button" className="button danger" onClick={()=>open('confirm',{title:current.trashed?'永久删除资产':'移入回收站',text:current.trashed?'删除后素材无法恢复，使用此素材的项目可能无法预览或导出。':'资产可以从回收站恢复。',danger:true,action:async()=>{if(current.trashed)await api(`/assets/${asset.id}`,{method:'DELETE'});else await patch(`/assets/${asset.id}`,{trashed:true});await refresh();}})}><Trash2 size={15}/></button><button className="button primary" disabled={busy}>保存</button></div></form></div></Modal>;}
function SkillPicker({spec}:{spec:any}){const{data,close}=useStudio();const[query,setQuery]=useState('');return <Modal title="选择技能" onClose={close}><SearchBox value={query} onChange={setQuery} placeholder="搜索技能"/><div className="skill-picker-list">{data.skills.filter(s=>s.name.includes(query)).map(s=><button key={s.id} onClick={()=>{spec?.select?.(s.name);close();}}><img src={s.image} alt=""/><span><b>{s.name}</b><small>{s.description}</small></span><Plus size={16}/></button>)}</div></Modal>;}
function SkillDetail({skill}:{skill:Skill}){const{close,createProject,open}=useStudio();const[prompt,setPrompt]=useState('');return <Modal title={skill.name} onClose={close}><img className="skill-detail-image" src={skill.image} alt=""/><p className="modal-copy">{skill.description}</p><label className="form-field">创作需求<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={4} placeholder="描述你的故事或创作想法"/></label><div className="modal-actions">{skill.custom&&<button className="button" onClick={()=>open('create-skill',skill)}><Pencil size={15}/>编辑</button>}<button className="button primary" onClick={()=>void createProject(skill.name,skill.name,prompt)}><Zap size={16}/>开始创作</button></div></Modal>;}
function SkillForm({skill}:{skill?:Skill}){const{close,refresh,notify}=useStudio();const[name,setName]=useState(skill?.name||'');const[description,setDescription]=useState(skill?.description||'');const[instructions,setInstructions]=useState(skill?.instructions||'');const[category,setCategory]=useState(skill?.category||'自媒体');const[busy,setBusy]=useState(false);return <Modal title={skill?'编辑技能':'创建我的技能'} onClose={close}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{if(skill)await patch(`/skills/${skill.id}`,{name,description,instructions,category});else await post('/skills',{name,description,instructions,category});await refresh();notify('技能已保存');close();}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}}><label className="form-field">技能名称<input required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label className="form-field">分类<select value={category} onChange={e=>setCategory(e.target.value)}>{['自媒体','广告营销','游戏','短漫剧','周边设计'].map(c=><option key={c}>{c}</option>)}</select></label><label className="form-field">简介<input value={description} maxLength={500} onChange={e=>setDescription(e.target.value)}/></label><label className="form-field">技能指令<textarea required rows={8} value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="定义角色、工作步骤、输出格式与确认节点"/></label><div className="modal-actions"><button className="button primary" disabled={busy||!name.trim()||!instructions.trim()}>保存技能</button></div></form></Modal>;}
function WorkDetail({work}:{work:Work}){const{close,createProject,favorite,data}=useStudio();return <Modal title={work.title} wide className="work-modal" onClose={close}><div className="work-preview">{work.video?<video src={work.video} controls autoPlay/>:<img src={work.image} alt={work.title}/>}</div><div className="work-detail-footer"><div><h3>{work.title}</h3><p className="muted">{work.description||work.category}</p>{!work.video&&<small className="muted">仅收录公开封面，原作品视频尚未导入。</small>}</div><IconButton label="收藏作品" onClick={()=>void favorite(work.id)}><Star fill={data.favorites.includes(work.id)?'currentColor':'none'} size={18}/></IconButton><button className="button primary" onClick={()=>void createProject(`${work.title} · 创作`, '爆款复刻',`创作主题：${work.title}`)}>创作同款<ArrowRight size={15}/></button></div></Modal>;}
function Publish({spec}:{spec:any}){const{close,data,refresh,notify}=useStudio();const[title,setTitle]=useState('');const[description,setDescription]=useState('');const[video,setVideo]=useState(spec?.video||'');const[category,setCategory]=useState('个人/自媒体');const[busy,setBusy]=useState(false);return <Modal title="发布到本地作品库" onClose={close}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await post('/works',{title,description,video,image:'/assets/work-0.webp',category});await refresh();notify('已发布到本地作品库，未上传至原站');close();}catch(e){notify((e as Error).message,true);}finally{setBusy(false);}}}><label className="form-field">作品标题<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="form-field">视频素材<select required value={video} onChange={e=>setVideo(e.target.value)}><option value="">选择视频</option>{spec?.video&&<option value={spec.video}>导出的视频</option>}{data.assets.filter(a=>a.mime.startsWith('video/')&&!a.trashed).map(a=><option value={a.url} key={a.id}>{a.name}</option>)}</select></label><label className="form-field">分类<select value={category} onChange={e=>setCategory(e.target.value)}>{industries.map(v=><option key={v}>{v}</option>)}</select></label><label className="form-field">简介<textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="status-note"><Info size={16}/>仅保存到本地作品库，不进行互联网发布。</div><div className="modal-actions"><button className="button primary" disabled={busy||!video||!title.trim()}>发布作品</button></div></form></Modal>;}
function Pricing(){const{close,notify}=useStudio();const[tab,setTab]=useState('个人');const[period,setPeriod]=useState('年付');const plans=[['BASE',999,133,1310],['STAR',2868,399,3930],['PRO',6108,1064,9550],['APEX',11988,2394,19860]] as const;return <Modal title="会员订阅" wide className="pricing-modal" onClose={close}><div className="pricing-heading"><small>双节特惠 · 原站方案展示</small><h2>年付会员限时折扣，享 <span>3</span> 倍盒饭</h2><p>Seedance 2.5 720p · 限时低至 0.32 元/秒</p></div><div className="pricing-tabs"><Tabs values={['个人','团队','企业']} value={tab} onChange={setTab}/><Tabs values={['年付','季付','月付']} value={period} onChange={setPeriod} pills/></div>{tab==='个人'?<div className="pricing-grid">{plans.map(([name,year,month,credits],i)=><article className={`plan plan-${i}`} key={name}><h3>{name}</h3><div className="plan-price">¥ {period==='年付'?year:period==='月付'?month:Math.round(month*2.7)}<small>/{period==='年付'?'年':period==='月付'?'月':'季'}</small></div><p><Coins size={15}/>{credits} / 月</p><button className={`button ${i===3?'lime':'white'}`} onClick={()=>notify('本地复刻未接入支付服务，不会发起扣款。')}>订阅</button><div className="plan-divider">会员专属模型</div>{['Seedance 2.5','Seedance2.0 Pro / Fast / mini','MiniMax H3 Max Turbo','Oii Image 2.5 Fast','高优先级生成队列','作品下载'].map(v=><div className="plan-feature" key={v}><Check size={14}/>{v}</div>)}</article>)}</div>:<Empty title={tab==='团队'?'团队服务尚未接入':'企业服务尚未接入'}><p>团队成员、权限与账单需要独立服务支持。</p></Empty>}<p className="pricing-disclaimer">页面用于原站界面对照。价格记录于 2026-09-27，不构成本地服务报价，支付未接入。</p></Modal>;}
function SettingsPanel(){const{data,close,refresh,notify}=useStudio();const[name,setName]=useState(data.profile.name);return <Modal title="设置" onClose={close}><label className="form-field">昵称<input value={name} maxLength={160} onChange={e=>setName(e.target.value)}/></label><button className="button" onClick={async()=>{try{await patch('/profile',{name});await refresh();notify('昵称已更新');}catch(e){notify((e as Error).message,true);}}}>保存</button><div className="settings-section"><h3>生成服务</h3><div className={`provider-state ${data.provider.configured?'connected':''}`}><span/>{data.provider.name}</div><p>在项目 .env 中配置 GENERATION_ENDPOINT 和 GENERATION_API_KEY，然后重启服务。密钥仅由本机服务读取，不存入浏览器。</p><p>原站模型名称是界面对照项。可用模型及参数由接入的服务决定。</p></div><div className="settings-section"><h3>数据与隐私</h3><p>项目和素材仅存于本地 data 目录。此版本为单用户本地应用，无正式身份认证；不应直接公开部署。</p><button className="button" onClick={()=>downloadJson({projects:data.projects,assets:data.assets,skills:data.skills.filter(s=>s.custom)},'studio-backup.json')}><Download size={16}/>导出数据清单</button></div></Modal>;}
function Notifications(){const{data,close,refresh,notify}=useStudio();return <Modal title="消息" onClose={close}><button className="text-button" onClick={async()=>{try{await post('/notifications/read',{});await refresh();}catch(e){notify((e as Error).message,true);}}}>全部标记已读</button><div className="notification-list">{data.notifications.map(n=><article key={n.id}><span className={n.read?'':'unread-dot'}/><div><h3>{n.title}</h3><p>{n.text}</p></div></article>)}</div></Modal>;}
function Balance(){const{data,close,open}=useStudio();return <Modal title="余额" onClose={close}><div className="balance-amount"><Coins size={30}/><strong>{data.profile.credits}</strong><span>本地测试积分</span></div><p className="modal-copy muted">测试积分仅用于本地界面验证，不等于原站盒饭，不支持充值或兑换。</p><button className="button" onClick={()=>open('pricing')}>查看订阅界面</button></Modal>;}
function Login({spec}:{spec:any}){const{close,notify}=useStudio();const[tab,setTab]=useState('手机号');return <Modal title="注册 / 登录" className="login-modal" onClose={close}><div className="login-brand"><img src="/assets/director.png" alt=""/><h2>注册 / 登录领积分哦</h2></div><Tabs values={['手机号','邮箱']} value={tab} onChange={setTab} pills/><label className="form-field">{tab}<input disabled placeholder={tab==='手机号'?'请输入手机号':'请输入邮箱'}/></label><div className="status-note"><LockKeyhole size={16}/>短信、邮箱与第三方登录尚未接入。请使用本地体验会话。</div><button className="button primary full" onClick={()=>{spec?.done?.();close();notify('已进入本地体验会话');}}><UserRound size={16}/>进入本地工作室</button><small className="login-note">无需输入原站账号、密码或验证码。</small></Modal>;}
function InfoPanel({type}:{type:string}){const{close}=useStudio();const titles:Record<string,string>={help:'帮助',license:'创作许可',activity:'活动',desktop:'桌面端',contact:'联系我们'};return <Modal title={titles[type]||'详情'} onClose={close}>{type==='help'?<div className="help-content"><details open><summary>项目保存在哪里？</summary><p>项目保存在本地 SQLite 数据库，上传素材保存在 data/uploads。</p></details><details><summary>如何生成图片或视频？</summary><p>需要配置独立生成服务；原站账号并不能直接授权本地调用其模型。</p></details><details><summary>如何导出？</summary><p>画布支持项目 JSON 导出。剪辑台支持上传素材的无声 MP4 画面合成。</p></details></div>:<p className="modal-copy">{type==='license'?'这是独立的本地复刻项目，不是 OiiOii 官方产品。原站名称与公开视觉素材保留其原有权利。生产部署前请替换为获得授权的品牌和素材。':type==='desktop'?'当前提供本地网页应用，未构建桌面安装包。':type==='activity'?'活动仅作为原站界面对照，本地应用不参加原站抽奖、奖励或推广活动。':'此项目独立运行，没有接入原站客服或微信。'}</p>}</Modal>;}
function AssetPicker({spec}:{spec:any}){const{data,close,upload}=useStudio();const[query,setQuery]=useState('');const[category,setCategory]=useState('全部');return <Modal title="资产库" wide onClose={close}><div className="modal-toolbar"><Tabs values={['全部','角色','场景','道具','其他']} value={category} onChange={setCategory} pills/><SearchBox value={query} onChange={setQuery} placeholder="搜索资产"/></div><div className="picker-assets">{data.assets.filter(a=>!a.trashed&&(category==='全部'||a.category===category)&&a.name.includes(query)).map(a=><button key={a.id} onClick={()=>{spec?.select?.(a);close();}}>{a.mime.startsWith('image/')?<img src={a.url} alt=""/>:<Film size={32}/>}<span>{a.name}</span></button>)}</div><FileDrop onFiles={async f=>{const a=await upload(f);if(a[0]){spec?.select?.(a[0]);close();}}}/></Modal>;}
